package com.rex.lifetracker.utils

import android.graphics.Color

object Constant {
    const val TAG = "TAG"

    const val BASE_URL = "https://maps.googleapis.com/"

    const val ACTION_START_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val STOP_SERVICE_ACTION = "STOP_SERVICE_ACTION"
    const val STOP_SERVICE_ACTION_CALL = "STOP_SERVICE_ACTION_CALL"
    const val ACTION_STOP_SERVICES = "ACTION_STOP_SERVICES"
    const val ACTION_WOMEN_SAFETY_SERVICE = "ACTION_WOMEN_SAFETY_SERVICE"
    const val CANCEL_ACTION = "CANCEL_ACTION"
    const val START_PHONE_SERVICES = "START_PHONE_SERVICES"
    const val START_ACTIVITY_FROM_NOTIFICATION = "START_ACTIVITY_FROM_NOTIFICATION"

    const val REQUEST_PERMISSION = 5
    const val REQUESTED_PERMISSION_CODE = 100
    const val REQUEST_STORAGE_READ_WRITE_CODE = 500

    const val ACTIVITY_REQUEST_CODE = 0
    const val GPS_PERMISSION_CODE = 2566
    const val BROADCAST_REQUEST_CODE = 200
    const val BROADCAST_REQUEST_CODE2 = 201

    const val CHANNEL_ID = "Bike"
    const val CHANNEL_ALERT_SYSTEM_ID = "CHANNEL_ALERT_SYSTEM_ID"
    const val CHANNEL_ALERT2_SYSTEM_ID = "CHANNEL_ALERT2_SYSTEM_ID"
    const val WOMEN_SAFETY_CHANNEL_ID = "WOMEN_SAFETY_CHANNEL_ID"
    const val CHANNEL_ID_CALLING = "CHANNEL_ID_CALLING"


    const val FOREGROUND_NOTIFICATION_ID = 1
    const val FOREGROUND_NOTIFICATION_ID2 = 5
    const val MOTION_ALERT_SYSTEM_NOTIFICATION_ID = 2
    const val MOTION_ALERT_SYSTEM_NOTIFICATION_ID2 = 3
    const val WOMEN_SAFETY_NOTIFICATION_ID = 4


    const val LOCATION_UPDATE_INTERVAL = 5000L
    const val FASTEST_LOCATION_INTERVAL = 2000L
    const val POLYLINE_COLOR = Color.TRANSPARENT
    const val POLYLINE_WIDTH = 8f
    const val MAP_ZOOM = 17f
}